/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.miras.APP;

import be.miras.BLL.EducationBLL;
import be.miras.DOMAIN.Education;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author shaun
 */
public class AdminEducationPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminEducationPanel
     */
    public AdminEducationPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEducationName = new javax.swing.JTextField();
        lblCourseName = new javax.swing.JLabel();
        lblEducation = new javax.swing.JLabel();
        txtEducationID = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lEducations = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(500, 500));

        lblCourseName.setText("Education Name:");

        lblEducation.setText("Education ID:");

        txtEducationID.setEditable(false);

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lEducations.setModel(new javax.swing.AbstractListModel<String>(){
            ArrayList<String>nameEducations = getArrayListEducations();
            public int getSize() { return nameEducations.size(); }
            public String getElementAt(int i) { return nameEducations.get(i);}
        }
    );
    lEducations.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            lEducationsMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(lEducations);

    jLabel1.setText("All educations:");

    btnRefresh.setText("Refresh");
    btnRefresh.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnRefreshActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblCourseName)
                        .addComponent(lblEducation))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtEducationID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEducationName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(btnCreate)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnDelete)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnUpdate)
                        .addComponent(btnRefresh))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEducation)
                    .addComponent(txtEducationID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCourseName)
                        .addComponent(txtEducationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(28, 28, 28)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCreate)
                        .addComponent(btnDelete)
                        .addComponent(btnUpdate))
                    .addGap(18, 18, 18)
                    .addComponent(btnRefresh))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        Education edu = new Education();
        EducationBLL edubll = new EducationBLL();
        ArrayList<Education> educations = new ArrayList<>();

        educations = edubll.GetAll();
        edu.setID(educations.size() + 1);
        int id = edu.getID();
        //edu.setID(id);
        edu.setName(txtEducationName.getText());
        edubll.Create(edu);
        JOptionPane.showMessageDialog(null, edu.getName() + " has been Created. Click refresh list to update.");
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        EducationBLL edubll = new EducationBLL();
        Education edu = new Education();
        String selected = lEducations.getSelectedValue().toString();

        edu = edubll.getByName(selected);
        edubll.Delete(edu);
        JOptionPane.showMessageDialog(null, edu.getName() + " has been removed. Click refresh list to update.");

        txtEducationID.setText("");
        txtEducationName.setText("");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        Education edu = new Education(Integer.parseInt(txtEducationID.getText()), txtEducationName.getText());
        EducationBLL edubll = new EducationBLL();
        edubll.Update(edu);
        JOptionPane.showMessageDialog(null, edu.getName() + " has been updated. Click refresh list to update.");

        txtEducationID.setText("");
        txtEducationName.setText("");
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void lEducationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lEducationsMouseClicked
        // TODO add your handling code here:
        String selected = lEducations.getSelectedValue().toString();
        EducationBLL edubll = new EducationBLL();
        Education edu = new Education();
        edu = edubll.getByName(selected);

        txtEducationID.setText(Integer.toString(edu.getID()));
        txtEducationName.setText(edu.getName());
    }//GEN-LAST:event_lEducationsMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        EducationBLL edubll = new EducationBLL();
        ArrayList<Education> educations = edubll.GetAll();
        DefaultListModel<String> listModel = new DefaultListModel<>();
        ArrayList<String> educationNames = new ArrayList<>();
        for (int i = 0; i < educations.size(); i++) {
            educationNames.add(educations.get(i).getName());
        }
        educationNames.forEach((i) -> {
            listModel.addElement(i);
        });
        lEducations.setModel(listModel);
    }//GEN-LAST:event_btnRefreshActionPerformed
    public ArrayList getArrayListEducations() {

        EducationBLL edubll = new EducationBLL();
        ArrayList<Education> educations = edubll.GetAll();
        ArrayList<String> nameEducations = new ArrayList<>();

        for (int i = 0; i < educations.size(); i++) {
            Education edu = new Education();
            edu = educations.get(i);
            nameEducations.add(edu.getName());
        }
        return nameEducations;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lEducations;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblEducation;
    private javax.swing.JTextField txtEducationID;
    private javax.swing.JTextField txtEducationName;
    // End of variables declaration//GEN-END:variables
}
