/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.miras.APP;

import be.miras.BLL.UserBLL;
import be.miras.DOMAIN.User;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author shaun
 */
public class AdminUserPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminStudentPanel
     */
    public AdminUserPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupRole = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        listUsers = new javax.swing.JList<>();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        lblAllUsers = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnStudent = new javax.swing.JRadioButton();
        btnAdmin = new javax.swing.JRadioButton();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();

        listUsers.setModel(new javax.swing.AbstractListModel<String>() {
            ArrayList<String>nameUsers = getArrayListUsers();
            public int getSize() { return nameUsers.size(); }
            public String getElementAt(int i) { return nameUsers.get(i); }

        });
        listUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listUsersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listUsers);

        lblEmail.setText("Email:");

        lblPassword.setText("Password:");

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete user");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh List");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        lblAllUsers.setText("All users:");

        btnUpdate.setText("Update user");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnGroupRole.add(btnStudent);
        btnStudent.setText("Student");

        btnGroupRole.add(btnAdmin);
        btnAdmin.setText("Administration");

        lblID.setText("ID:");

        txtID.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPassword)
                            .addComponent(lblEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail)
                            .addComponent(txtPassword)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnStudent)
                                .addGap(18, 18, 18)
                                .addComponent(btnAdmin))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblID)
                                .addGap(55, 55, 55)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAllUsers)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblAllUsers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRefresh)
                            .addComponent(btnCreate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblID)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPassword)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStudent)
                            .addComponent(btnAdmin))
                        .addGap(52, 52, 52)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listUsersMouseClicked
        String selected = listUsers.getSelectedValue().toString();
        /*
        //get the first part of the selected item (lastname)
        if (selected.contains(" ")) {
            selected = selected.substring(0, selected.indexOf(" "));

        }
         */
        UserBLL userbll = new UserBLL();
        User u = new User();
        u = userbll.getByEmail(selected);
        txtID.setText(Integer.toString(u.getID()));
        txtPassword.setText(u.getPassword());
        txtEmail.setText(u.getEmail());
        if (u.getRoleID() == 1) {
            btnAdmin.setSelected(true);
        } else {
            btnStudent.setSelected(true);
        }


    }//GEN-LAST:event_listUsersMouseClicked

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        //PersonBLL personbll = new PersonBLL();
        UserBLL userbll = new UserBLL();
        //   Person person = new Person();

        User user = new User();

        String selected = listUsers.getSelectedValue().toString();
        /*if (selected.contains(" ")) {
            selected = selected.substring(0, selected.indexOf(" "));

        }*/
        user = userbll.getByEmail(selected);
        /*
        String email = person.getFirstname() + person.getLastname() + "@gmail.com";
        user = userbll.getByEmail(email);
        System.out.println(email);
        // personbll.Delete(person);
         */
        userbll.Delete(user);
        JOptionPane.showMessageDialog(null, user.getEmail() + " has been removed. Click refresh list to update.");

        txtEmail.setText("");
        txtPassword.setText("");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:

        UserBLL ubll = new UserBLL();
        ArrayList<User> users = ubll.GetAll();
        DefaultListModel<String> listModel = new DefaultListModel<>();
        ArrayList<String> userNames = new ArrayList<>();
        for (int i = 0; i < users.size(); i++) {
            userNames.add(users.get(i).getEmail());
        }
        userNames.forEach((i) -> {
            listModel.addElement(i);
        });
        listUsers.setModel(listModel);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed

        User user = new User();
        UserBLL u = new UserBLL();
        ArrayList<User> users = new ArrayList<>();

        users = u.GetAll();

        user.setID(users.size() + 1);
        //    int id = user.getID();

        user.setEmail(txtEmail.getText());
        user.setPassword(txtPassword.getText());
        //bll plz

        if (btnAdmin.isSelected()) {
            user.setRoleID(1);
        } else {
            user.setRoleID(2);
        }

        u.Create(user);
        JOptionPane.showMessageDialog(null, user.getEmail() + " has been Created. Click refresh list to update.");

    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        User u = new User(Integer.parseInt(txtID.getText()), txtEmail.getText(), txtPassword.getText());
        if (btnAdmin.isSelected()) {
            u.setRoleID(1);
        } else {
            u.setRoleID(2);
        }

        UserBLL ubll = new UserBLL();
        ubll.Update(u);
        txtID.setText("");
        txtEmail.setText("");
        txtPassword.setText("");
        JOptionPane.showMessageDialog(null, u.getEmail() + " has been Updated. Click refresh list to update.");
    }//GEN-LAST:event_btnUpdateActionPerformed
    public ArrayList getArrayListUsers() {
        UserBLL u = new UserBLL();
        ArrayList<User> users = u.GetAll();
        ArrayList<String> nameUsers = new ArrayList<>();

        for (int i = 0; i < users.size(); i++) {
            User pe = new User();
            pe = users.get(i);
            nameUsers.add(pe.getEmail());
        }
        return nameUsers;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAdmin;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.ButtonGroup btnGroupRole;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JRadioButton btnStudent;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAllUsers;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JList<String> listUsers;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
