/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.miras.APP;

import be.miras.BLL.CourseBLL;
import be.miras.BLL.EducationBLL;
import be.miras.BLL.Education_CourseBLL;
import be.miras.DOMAIN.Course;
import be.miras.DOMAIN.Education;
import be.miras.DOMAIN.Education_Course;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author shaun
 */
public class AdminCoursePanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminCoursePanel
     */
    public AdminCoursePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEndD = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        spDescription = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        lblCourses = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lCourses = new javax.swing.JList<>();
        txtCourseName = new javax.swing.JTextField();
        txtHours = new javax.swing.JTextField();
        lblCourseID = new javax.swing.JLabel();
        dpStart = new org.jdesktop.swingx.JXDatePicker();
        lblCourseName = new javax.swing.JLabel();
        dpEnd = new org.jdesktop.swingx.JXDatePicker();
        lblHours = new javax.swing.JLabel();
        txtCourseID = new javax.swing.JTextField();
        lblStartD = new javax.swing.JLabel();
        lblEducation = new javax.swing.JLabel();
        txtEducationID = new javax.swing.JTextField();
        cbCourses = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnUpdate = new javax.swing.JToggleButton();

        setPreferredSize(new java.awt.Dimension(500, 500));

        lblEndD.setText("End date:");

        btnRefresh.setText("Refresh");
        btnRefresh.setPreferredSize(new java.awt.Dimension(80, 25));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel1.setText("Description:");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        spDescription.setViewportView(txtDescription);

        lblCourses.setText("All Courses:");

        lCourses.setModel(new javax.swing.AbstractListModel<String>() {
            ArrayList<String>courses = getAllCourses();
            public int getSize() { return courses.size(); }
            public String getElementAt(int i) { return courses.get(i); }

        });
        lCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lCoursesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lCourses);

        lblCourseID.setText("Course ID:");

        lblCourseName.setText("Course Name:");

        lblHours.setText("Hours:");

        txtCourseID.setEditable(false);

        lblStartD.setText("Start date:");

        lblEducation.setText("Education ID:");

        txtEducationID.setEditable(false);

        EducationBLL e = new EducationBLL();
        ArrayList<Education> educations = e.GetAll();
        //String[]opleidingarray = opleidingen.toArray(new String[opleidingen.size()]);
        //String[]opleidingArray = educations.size();
        ArrayList<String> opleidingen = new ArrayList<String>();
        for(Education o : educations){
            opleidingen.add(o.getName());
        }
        String[]opleidingarray = opleidingen.toArray(new String[opleidingen.size()]);
        cbCourses.setModel(new javax.swing.DefaultComboBoxModel<>(opleidingarray));

        jLabel2.setText("Part of:");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDel.setText("Delete");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEducation)
                        .addGap(18, 18, 18)
                        .addComponent(txtEducationID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCourseID)
                        .addGap(33, 33, 33)
                        .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(lblCourses))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCourseName)
                            .addComponent(lblHours)
                            .addComponent(lblStartD)
                            .addComponent(lblEndD)
                            .addComponent(jLabel1))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHours, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dpStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dpEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(49, 49, 49)
                                .addComponent(cbCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(152, 152, 152))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEducationID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblEducation)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lblCourseID))
                    .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCourses))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblCourseName)
                        .addGap(13, 13, 13)
                        .addComponent(lblHours)
                        .addGap(19, 19, 19)
                        .addComponent(lblStartD)
                        .addGap(11, 11, 11)
                        .addComponent(lblEndD)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(txtHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(dpStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(dpEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(spDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd)
                        .addComponent(btnDel))
                    .addComponent(btnUpdate))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        Education_CourseBLL ecbll = new Education_CourseBLL();
        Education_Course ec = new Education_Course();
        CourseBLL cbll = new CourseBLL();
        Course c = new Course();
        String selected = lCourses.getSelectedValue().toString();

        c.setID(Integer.parseInt(txtCourseID.getText()));
        c.setName(selected);

        cbll.Delete(c);

        ec.setEducationID(Integer.parseInt(txtEducationID.getText()));
        ec.setCourseID(Integer.parseInt(txtCourseID.getText()));

        ecbll.Delete(ec);
        JOptionPane.showMessageDialog(null, c.getName() + " has been Deleted. Click refresh list to update.");
    }//GEN-LAST:event_btnDelActionPerformed

    private void lCoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lCoursesMouseClicked
        // TODO add your handling code here:
        String selected = lCourses.getSelectedValue().toString();

        Education_CourseBLL ecbll = new Education_CourseBLL();
        // selected search here
        CourseBLL cbl = new CourseBLL();
        //getbyname returns course object
        Course c = cbl.getByName(selected);
        //find educqtionid by course id
        int courseid = c.getID();
        //search for education id
        String eduID = Integer.toString(ecbll.getEduByCourseID(courseid));
        //place id in education id label
        txtEducationID.setText(eduID);
        //place course id in course id lqbel
        txtCourseID.setText(Integer.toString(courseid));
        EducationBLL edubll = new EducationBLL();
        Education edu = new Education();
        edu = edubll.GetById(Integer.parseInt(eduID));

        txtCourseName.setText(c.getName());
        txtHours.setText(Integer.toString(c.getHours()));
        dpStart.setDate(c.getStartDate());
        dpEnd.setDate(c.getEndDate());
        txtDescription.setText(c.getDescription());
        cbCourses.setSelectedItem(edu.getName());


    }//GEN-LAST:event_lCoursesMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        CourseBLL cbll = new CourseBLL();
        Course c = new Course();
        ArrayList<Course> courses = cbll.GetAll();
        DefaultListModel<String> listModel = new DefaultListModel<>();
        ArrayList<String> courseNames = new ArrayList<>();

        for (int i = 0; i < courses.size(); i++) {
            courseNames.add(courses.get(i).getName());
        }
        courseNames.forEach((i) -> {
            listModel.addElement(i);
        });

        lCourses.setModel(listModel);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:

        EducationBLL edubll = new EducationBLL();
        Education edu = new Education();
        Education_CourseBLL ecbll = new Education_CourseBLL();
        Education_Course ec = new Education_Course();

        CourseBLL cbll = new CourseBLL();
        Course c = new Course();
        ArrayList<Course> allcourses = cbll.GetAll();
        System.out.println(allcourses.size());
        //WAAROM ???
        c.setID(allcourses.size() + 3);
        c.setName(txtCourseName.getText());
        c.setHours(Integer.parseInt(txtHours.getText()));
        c.setStartDate(dpStart.getDate());
        c.setEndDate(dpEnd.getDate());
        c.setDescription(txtDescription.getText());

        cbll.Create(c);

        edu.setID(edubll.getByName(cbCourses.getSelectedItem().toString()).getID());
        edu.setName(cbCourses.getSelectedItem().toString());

        ec.setCourseID(c.getID());
        ec.setEducationID(edu.getID());

        ecbll.Create(ec);
        JOptionPane.showMessageDialog(null, c.getName() + " has been added to " + edu.getName() + ". Click refresh list to update.");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        CourseBLL cbll = new CourseBLL();
        Course c = new Course();
        c.setID(Integer.parseInt(txtCourseID.getText()));
        c.setName(txtCourseName.getText());
        c.setHours(Integer.parseInt(txtHours.getText()));
        c.setStartDate(dpStart.getDate());
        c.setEndDate(dpEnd.getDate());
        c.setDescription(txtDescription.getText());

        cbll.Update(c);

        EducationBLL edubll = new EducationBLL();
        Education edu = new Education();
        Education_CourseBLL ecbll = new Education_CourseBLL();
        Education_Course ec = new Education_Course();

        edu.setID(edubll.getByName(cbCourses.getSelectedItem().toString()).getID());
        edu.setName(cbCourses.getSelectedItem().toString());

        ec.setCourseID(c.getID());
        ec.setEducationID(edu.getID());

        ecbll.Create(ec);

        txtEducationID.setText("");
        txtCourseID.setText("");
        txtCourseName.setText("");
        txtHours.setText("");
        Date d = new Date();
        dpStart.setDate(d);
        dpEnd.setDate(d);
        txtDescription.getText();

        JOptionPane.showMessageDialog(null, c.getName() + " has been Updated. Click refresh list to update.");

    }//GEN-LAST:event_btnUpdateActionPerformed

    public ArrayList<String> getAllCourses() {
        CourseBLL cbl = new CourseBLL();
        ArrayList<Course> courses = new ArrayList<>();
        courses = cbl.GetAll();
        ArrayList<String> courseNames = new ArrayList<>();
        for (Course c : courses) {
            courseNames.add(c.getName());
        }
        return courseNames;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JToggleButton btnUpdate;
    private javax.swing.JComboBox<String> cbCourses;
    private org.jdesktop.swingx.JXDatePicker dpEnd;
    private org.jdesktop.swingx.JXDatePicker dpStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lCourses;
    private javax.swing.JLabel lblCourseID;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblCourses;
    private javax.swing.JLabel lblEducation;
    private javax.swing.JLabel lblEndD;
    private javax.swing.JLabel lblHours;
    private javax.swing.JLabel lblStartD;
    private javax.swing.JScrollPane spDescription;
    private javax.swing.JTextField txtCourseID;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtEducationID;
    private javax.swing.JTextField txtHours;
    // End of variables declaration//GEN-END:variables

}
