/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.miras.APP;

import be.miras.BLL.CourseBLL;
import be.miras.BLL.EnrolmentBLL;
import be.miras.BLL.UserBLL;
import be.miras.DOMAIN.Course;
import be.miras.DOMAIN.Enrolment;
import be.miras.DOMAIN.User;
import java.util.ArrayList;

/**
 *
 * @author shaun
 */
public class StudentHome extends javax.swing.JPanel {

    /**
     * Creates new form StudentHome
     */
    public StudentHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEnrolment = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lEnrolments = new javax.swing.JList<>();
        lblCourseID = new javax.swing.JLabel();
        lblCourseName = new javax.swing.JLabel();
        lblHours = new javax.swing.JLabel();
        lblStartD = new javax.swing.JLabel();
        lblEndD = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        spDescription = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        txtCouseName = new javax.swing.JTextField();
        txtHours = new javax.swing.JTextField();
        dpStart = new org.jdesktop.swingx.JXDatePicker();
        dpEnd = new org.jdesktop.swingx.JXDatePicker();
        txtCourseID = new javax.swing.JTextField();
        btnDisenrol = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(500, 500));

        lblEnrolment.setText("My enrolments:");

        lEnrolments.setModel(new javax.swing.AbstractListModel<String>() {
            ArrayList<String>courses = getAllCourses();
            public int getSize() { return courses.size(); }
            public String getElementAt(int i) { return courses.get(i); }

        });
        lEnrolments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lEnrolmentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lEnrolments);

        lblCourseID.setText("Course ID:");

        lblCourseName.setText("Course Name:");

        lblHours.setText("Hours:");

        lblStartD.setText("Start date:");

        lblEndD.setText("End date:");

        jLabel1.setText("Description:");

        txtDescription.setEditable(false);
        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        spDescription.setViewportView(txtDescription);

        txtCouseName.setEditable(false);

        txtHours.setEditable(false);

        dpStart.setEditable(false);

        dpEnd.setEditable(false);

        txtCourseID.setEditable(false);

        btnDisenrol.setText("Disenrol");
        btnDisenrol.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblCourseID)
                .addGap(33, 33, 33)
                .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCourseName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCouseName)
                            .addComponent(txtHours)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblHours)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblEndD)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dpEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblStartD)
                            .addGap(32, 32, 32)
                            .addComponent(dpStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(26, 26, 26)
                            .addComponent(spDescription))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDisenrol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEnrolment)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseID)
                    .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEnrolment, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCourseName)
                        .addComponent(txtCouseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHours)
                            .addComponent(txtHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStartD)
                            .addComponent(dpStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEndD)
                            .addComponent(dpEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(spDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDisenrol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 188, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lEnrolmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lEnrolmentsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lEnrolmentsMouseClicked
    public ArrayList<String> getAllCourses() {

        CourseBLL cbl = new CourseBLL();
        ArrayList<Course> courses = new ArrayList<>();
        courses = cbl.GetAll();
        ArrayList<String> courseNames = new ArrayList<>();
        for (Course c : courses) {
            courseNames.add(c.getName());
        }
        UserBLL ubll = new UserBLL();
        User user = new User();

        GUI g = new GUI();
        user = g.getLoggedIn();

        int userID = user.getID();

        Enrolment e = new Enrolment();
        EnrolmentBLL ebll = new EnrolmentBLL();
        //  ArrayList<Enrolment> allEnrols = ebll.

        // e = ebll.GetById(userID);
        return courseNames;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisenrol;
    private org.jdesktop.swingx.JXDatePicker dpEnd;
    private org.jdesktop.swingx.JXDatePicker dpStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lEnrolments;
    private javax.swing.JLabel lblCourseID;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblEndD;
    private javax.swing.JLabel lblEnrolment;
    private javax.swing.JLabel lblHours;
    private javax.swing.JLabel lblStartD;
    private javax.swing.JScrollPane spDescription;
    private javax.swing.JTextField txtCourseID;
    private javax.swing.JTextField txtCouseName;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtHours;
    // End of variables declaration//GEN-END:variables
}
