/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.miras.APP;

import be.miras.BLL.CourseBLL;
import be.miras.BLL.EducationBLL;
import be.miras.BLL.Education_CourseBLL;
import be.miras.DOMAIN.Course;
import be.miras.DOMAIN.Education;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author shaun
 */
public class StudentEducation extends javax.swing.JPanel {

    CourseBLL cBLL = new CourseBLL();
    EducationBLL eBLL = new EducationBLL();

    public StudentEducation() {
        initComponents();
    }

    /*public StudentEducation() {
        initComponents();
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEducations = new javax.swing.JLabel();
        spEducations = new javax.swing.JScrollPane();
        liEducations = new javax.swing.JList<>();
        txtCourseName = new javax.swing.JTextField();
        txtHours = new javax.swing.JTextField();
        lblStartD = new javax.swing.JLabel();
        lblEndD = new javax.swing.JLabel();
        dpStart = new org.jdesktop.swingx.JXDatePicker();
        lblDesciption = new javax.swing.JLabel();
        dpEnd = new org.jdesktop.swingx.JXDatePicker();
        txtCourseID = new javax.swing.JTextField();
        lblCourseID = new javax.swing.JLabel();
        spDescription = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        lblCourseName = new javax.swing.JLabel();
        lblHours = new javax.swing.JLabel();
        spCourses = new javax.swing.JScrollPane();
        liCourses = new javax.swing.JList<>();
        lblCourses = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 500));

        lblEducations.setText("Educations:");

        liEducations.setModel(new javax.swing.AbstractListModel<String>(){
            ArrayList<String>nameEducations = getArrayListEducations();
            public int getSize() { return nameEducations.size(); }
            public String getElementAt(int i) { return nameEducations.get(i);}
        }
    );
    liEducations.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            liEducationsMouseClicked(evt);
        }
    });
    spEducations.setViewportView(liEducations);

    txtCourseName.setEditable(false);

    txtHours.setEditable(false);

    lblStartD.setText("Start date:");

    lblEndD.setText("End date:");

    dpStart.setEditable(false);

    lblDesciption.setText("Description:");

    dpEnd.setEditable(false);

    txtCourseID.setEditable(false);
    txtCourseID.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtCourseIDActionPerformed(evt);
        }
    });

    lblCourseID.setText("Course ID:");

    txtDescription.setEditable(false);
    txtDescription.setColumns(20);
    txtDescription.setRows(5);
    spDescription.setViewportView(txtDescription);

    lblCourseName.setText("Course Name:");

    lblHours.setText("Hours:");

    liCourses.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            liCoursesMouseClicked(evt);
        }
    });
    spCourses.setViewportView(liCourses);

    lblCourses.setText("Courses:");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblEducations)
                .addComponent(spEducations, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(lblCourses))
                .addGroup(layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(spCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCourseID)
                                .addComponent(lblCourseName)
                                .addComponent(lblHours))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(txtHours, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblDesciption)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEndD)
                                    .addComponent(lblStartD))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dpStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dpEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
            .addContainerGap(209, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblCourseID)
                        .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCourseName)
                        .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHours)
                        .addComponent(txtHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dpStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblStartD))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEndD)
                        .addComponent(dpEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(17, 17, 17)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblDesciption)
                        .addComponent(spDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEducations)
                        .addComponent(lblCourses))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(spCourses, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                        .addComponent(spEducations))))
            .addGap(0, 208, Short.MAX_VALUE))
    );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCourseIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseIDActionPerformed

    private void liEducationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liEducationsMouseClicked
        ArrayList<Course> c = cBLL.GetByEdu(eBLL.getByName(liEducations.getSelectedValue()));

        DefaultListModel model = new DefaultListModel();
        for (Course temp : c) {
            model.addElement(temp.getName());
        }
        liCourses.setModel(model);

    }//GEN-LAST:event_liEducationsMouseClicked

    private void liCoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liCoursesMouseClicked
        // TODO add your handling code here:
        String selected = liCourses.getSelectedValue().toString();

        Education_CourseBLL ecbll = new Education_CourseBLL();
        // selected search here
        CourseBLL cbl = new CourseBLL();
        //getbyname returns course object
        Course c = cbl.getByName(selected);
        //find educqtionid by course id
        int courseid = c.getID();
        //search for education id
        String eduID = Integer.toString(ecbll.getEduByCourseID(courseid));
        //place id in education id label

        //place course id in course id lqbel
        txtCourseID.setText(Integer.toString(courseid));
        EducationBLL edubll = new EducationBLL();
        Education edu = new Education();
        edu = edubll.GetById(Integer.parseInt(eduID));

        txtCourseName.setText(c.getName());
        txtHours.setText(Integer.toString(c.getHours()));
        dpStart.setDate(c.getStartDate());
        dpEnd.setDate(c.getEndDate());
        txtDescription.setText(c.getDescription());
    }//GEN-LAST:event_liCoursesMouseClicked
    public ArrayList getArrayListEducations() {

        EducationBLL edubll = new EducationBLL();
        ArrayList<Education> educations = edubll.GetAll();
        ArrayList<String> nameEducations = new ArrayList<>();

        for (int i = 0; i < educations.size(); i++) {
            Education edu = new Education();
            edu = educations.get(i);
            nameEducations.add(edu.getName());
        }
        return nameEducations;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker dpEnd;
    private org.jdesktop.swingx.JXDatePicker dpStart;
    private javax.swing.JLabel lblCourseID;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblCourses;
    private javax.swing.JLabel lblDesciption;
    private javax.swing.JLabel lblEducations;
    private javax.swing.JLabel lblEndD;
    private javax.swing.JLabel lblHours;
    private javax.swing.JLabel lblStartD;
    private javax.swing.JList<String> liCourses;
    private javax.swing.JList<String> liEducations;
    private javax.swing.JScrollPane spCourses;
    private javax.swing.JScrollPane spDescription;
    private javax.swing.JScrollPane spEducations;
    private javax.swing.JTextField txtCourseID;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtHours;
    // End of variables declaration//GEN-END:variables
}
